FROM node:18.15-alpine

WORKDIR /usr/src/app
# Install app dependencies
# A wildcard is used to ensure both package.json AND 
# package-lock.json are copied where available (npm@5+)
COPY server-node/package.json ./
RUN yarn install
COPY server-node ./
#TODO - compile and copy the compiled code
RUN yarn build
# COPY ./server-node/dist .
EXPOSE 3042
CMD [ "node", "dist/index.js" ]
