FROM node:18.15-alpine

WORKDIR /usr/src/app
# Install app dependencies
# A wildcard is used to ensure both package.json AND 
# package-lock.json are copied where available (npm@5+)
COPY server-node/package.json ./

RUN yarn install
# If you are building your code for production
#TODO - mount the volume
#TODO - compile and copy the compiled code
COPY ./server-node .
EXPOSE 8080
CMD [ "node", "server.js" ]
